src/mpb_interface.jl, src/types.jl
If we don't keep a reference on the Julia side, then the object could be freed by the GC at any time and cause nasty segfaults when we try to access it from inside the callback.
=> keep a reference to callback userdata

deps/build.jl, src/SCIP.jl, src/mpb_interface.jl, test/more_tests.jl, test/runtests.jl
=> implements getsolvetime

src/mpb_interface.jl, src/params.jl, src/types.jl, src/wrapper.jl
I added two wrapper types and used the more specific method signatures, according to the MathProgBase documentation. For the common methods, I created a union type.
Related to discussion in #26.
=> Use proper model types for LinearQuadratic and Nonlinear interfaces

src/mpb_interface.jl
as per the change in MathProgBase and JuMP.
=> rename state :Other -> :Intermediate

REQUIRE, src/mpb_interface.jl, test/REQUIRE
Enables SCIP to work with JuMP 0.16. Good idea to release a new version following this.
=> Update bounds for MathProgBase

README.md
Hi,
I had the relatively tough time trying to get SCIP.jl working. This attempt is to make installing SCIP.jl easier for people who don't understand how to set ENV variables and including missing steps during installation. Also I got SCIP.jl working without copying the [patched file](http://scip.zib.de/download/bugfixes/scip-3.2.1/Makefile.doit), I think this step is no longer required.
=> Elaborated installation instruction

deps/csip_version.jl, src/SCIP.jl, src/csip_wrapper.jl, src/params.jl, src/types.jl
This will make it easier to distinguish between different solvers running (to solve subproblems in callbacks, say).
=> Allow prefix for all output from SCIP

src/MOI_wrapper.jl, test/MOI_additional.jl, test/runtests.jl
fixes #79 
Still needs additional tests. Maybe prints too many warnings now. Probably is too conservative (does not consider variable type when throwing error about existing bounds).
In particular, will still fail for these cases now:
- fixing a binary variable
- having two separate constraints, one for the lower bound, one for the upper bound
=> Deal with implicit and duplicate constraints for variable bounds

README.md, src/nonlinear.jl, src/wrapper/expr_manual.jl, test/MOI_nonlinear_exprs.jl
Unary `abs`, binary `min` and `max` as well as `^` with integer exponent.
Also updated README.
=> Support more operators in nonlinear expressions.

src/MOI_wrapper.jl, test/MOI_wrapper.jl
This adds mostly LP tests. Would still need to support `VectorAffineFunction` for the other conic tests :-(
=> Run more MOI tests, using the ScalarizeBridge

src/managed_scip.jl, test/MOI_additional.jl
This aims to restore the same functionality that was introduced in https://github.com/SCIP-Interfaces/SCIP.jl/pull/16, but I chose to have the type of parameter be fully guided by what SCIP thinks it should be (using `SCIPparamGetType`), rather than using dispatch on the Julia side. `cconvert` should take care of the rest.
Fixes #15.
=> Handle parameter types properly.

.travis.yml, deps/build.jl
Took about 5 minutes for the actual change and several hours to get Travis working. I initially wanted to use the precompiled binaries, but I ran into an illegal instruction on OSX, https://travis-ci.org/SCIP-Interfaces/SCIP.jl/jobs/512838942#L227, and decided to compile from source.
=> Add OSX support (+ Travis testing)

src/MOI_wrapper/variable.jl, test/MOI_wrapper.jl, test/MOI_wrapper_direct.jl, test/runtests.jl
- following discussion in https://github.com/JuliaOpt/MathOptInterface.jl/pull/697,
- use `MOIB.full_bridge_optimizer` for the MOI testsets,
- call individual tests (not testsets with exclusions) when using direct `Optimizer`.
Still need to exlude tests for a variety of reasons (can't query vars by name, SCIP's SOC constraints make strong assumptions about var bounds, can't delete vars from constraints), but feel more future-proof w.r.t. to new tests being added to MOI :smile:
=> Improve MOI test usage

src/MOI_wrapper/indicator_constraints.jl
guess who forgot to add a method definition for `IndicatorSet`
=> add dimension method for Indicator

.appveyor.yml, README.md, deps/build.jl
The package currently fails to build on Windows with the message `SCIP is currently not supported on "NT"`. This pull request fixes this by modifying `deps/build.jl` to search for the correct DLL. I have verified not only the package builds successfully with these changes, but also that all unit tests pass. 
The function `write_depsfile` needed to be modified because, on Windows, the `path` variable contains backslashes which need to be quoted.
=> Add Windows support

Project.toml, src/SCIP.jl, src/managed_scip.jl, src/util.jl, src/wrapper.jl, src/wrapper/manual_commons.jl, test/managed_scip.jl
Allows you to do e.g.
```julia
print_timing_statistics(mscip)
```
or
```julia
print_timing_statistics(mscip, filename)
```
The docstrings for these functions look like
```julia
help?> SCIP.print_timing_statistics
SCIP.print_timing_statistics(mscip::ManagedSCIP)
SCIP.print_timing_statistics(mscip::ManagedSCIP, file_descriptor::RawFD)
SCIP.print_timing_statistics(mscip::ManagedSCIP, stream::Union{Base.Filesystem.File, IOStream})
SCIP.print_timing_statistics(mscip::ManagedSCIP, filename::AbstractString)
Print statistics (calls SCIP.SCIPprintTimingStatistics).
The one-argument version prints to standard output.
Note that the method that takes a stream only applies to synchronous Files and IOStreams. In particular, it doesn't apply to stdout.
```
=> Add user-friendly interface for statistics printing functionality.

.appveyor.yml, .travis.yml
Version 6.0.2 not released properly yet:
> Note that currently, the download of the SCIP Optimization Suite 6.0.2 is a beta version of our upcoming bugfix release.
=> update CI scripts to use SCIP 6.0.2

src/MOI_wrapper/results.jl
- use `SCIPgetStatus` instead of `SCIPgetStage`
- use tuple of stages instead of array (avoid alloc)
=> fix assert_solved

src/MOI_wrapper/indicator_constraints.jl, test/MOI_wrapper_bridged.jl, test/MOI_wrapper_direct.jl
Adding the constant term to indicator constraints
=> Fix indicator

NEWS.md, Project.toml, src/MOI_wrapper.jl, src/MOI_wrapper/variable.jl, src/managed_scip.jl, test/MOI_additional.jl, test/MOI_wrapper_bridged.jl, test/MOI_wrapper_direct.jl
=> Support VariablePrimalStart

src/MOI_wrapper/nonlinear_constraints.jl, test/MOI_nonlinear_exprs.jl
=> Allow adding nonlinear constraints after solving

Project.toml, src/CEnum.jl, src/wrapper.jl
Attempt at implementing #174
Replace external dependency on older version of `CEnum` with a "local" submodule.
The aim is to prevent `SCIP` from holding back `CEnum`, which in turns holds back other packages (e.g. `Cbc`,  `Clp`).
In particular it would nice if the latest versions of `SCIP` and other solvers could coexist in the same environment.
=> RFC: Replace external dependency CEnum with private submodule

src/MOI_wrapper.jl, src/MOI_wrapper/linear_constraints.jl, src/MOI_wrapper/quadratic_constraints.jl, src/MOI_wrapper/sepa.jl, src/MOI_wrapper/variable.jl
The field for separators was set with a default "Nothing" instead of "nothing". This was adapted here.
Comparison with nothing is done with identity equality
=> switch data type Nothing to value

src/MOI_wrapper/results.jl
This might happen if a user limit (ie time) stops the solver during presolving.
Fixes a bug [encountered](https://github.com/NREL-SIIP/PowerSimulations.jl/runs/4467002116?check_suite_focus=true#step:5:316) by @jd-lara.
=> Allow stage PRESOLVING in assert_solved

src/MOI_wrapper/variable.jl, test/MOI_additional.jl, test/MOI_wrapper_cached.jl, test/runtests.jl
In addition, greatly simplify the MOI_wrapper_cached.jl file.
Thowing a `DeleteNotAllowed` will trigger the cache to rebuild the model. This means we can now run the full gamut of tests when using the cache. 
I don't know if there is value in running `_cached`, `_bridged`, and `_direct`. Perhaps we could delete the others? We really only care that the cache is working, and the number of excludes suggests that the rest of the API isn't fully implemented in direct mode.
=> Throw DeleteNotAllowed error when deleting variables

src/MOI_wrapper.jl, src/MOI_wrapper/objective.jl, test/MOI_wrapper_bridged.jl, test/MOI_wrapper_direct.jl
x-ref: https://github.com/jump-dev/MathOptInterface.jl/pull/2085
There are actually a bunch of excluded tests in SCIP. That's usually suggestive of bugs in the implementation.
=> Fix return value of ListOfModelAttributesSet

Project.toml, src/SCIP.jl, src/init.jl
`SCIP_PaPILO_jll` is precompiled with an upper bound on `Ipopt_jll`. We can't download the last artifact of `Ipopt_jll` when we use Ipopt.jl if SCIP.jl is installed.
I updated SCIP.jl such that a BLAS / LAPACK backend is automatically loaded. You should be able to drop this [constraint](https://github.com/JuliaPackaging/Yggdrasil/blob/master/S/SCIP_PaPILO/build_tarballs.jl#L71) in the future.
=> Update SCIP.jl to support Ipopt precompiled with LBT

src/MOI_wrapper.jl, src/MOI_wrapper/conflict.jl, test/MOI_conflicts.jl
Adding support for a conflict report based on solving an auxiliary problem with superindicators
=> Conflict report

src/MOI_wrapper/variable.jl, test/MOI_additional.jl
x-ref https://github.com/jump-dev/MathOptInterface.jl/pull/2318#issuecomment-1780291375
=> Fix is_valid for ZeroOne and Integer constraints in MOI wrapper

src/MOI_wrapper.jl, test/conshdlr.jl, test/scip_data.jl
This fix an issue with garbage collection when only the inner object of the optimizer is used as exemplified by the following example
```julia
import SCIP
function make_optimizer()
optimizer = SCIP.Optimizer()
return optimizer.inner
end
function run_test1()
scip_data = make_optimizer()
GC.gc(true)
@assert(scip_data.scip[] != C_NULL)
end
function run_test2()
scip_data = SCIP.Optimizer()
inner = scip_data.inner
scip_data = 0
GC.gc(true)
@assert(inner.scip[] != C_NULL)
end
GC.enable_logging(true)
run_test1()
run_test2()
```
The fix is to change the finalizer call to listen to garbage collection events for the SCIPdata object of the MOI Optimizer object instead of listen to garbage collection events for the whole MOI Optimizer object
=> Persistence Of SCIPData Object

README.md, src/init.jl
Our poor Windows users are ill-served by the current installation instructions.
Someone has been emailing me complaining of segfaults.
=> Update README with clarified Windows instructions

.github/workflows/MINLP.yml, .github/workflows/ci.yml, Project.toml, src/init.jl
Minimal necessary changes to test with SCIP 9. All tests pass locally, but there seems to be an issue in CI with julia 1.6.
#286
=> Minimal changes to support SCIP 9

src/MOI_wrapper.jl
This fix the issue mentioned in https://github.com/scipopt/SCIP.jl/issues/296.
When creating a model using JuMP, i.e. via `model = Model(SCIP.Optimizer)`. JuMP creates a model with Caching + Constraint Bridge activated. The way this works is during the `optimize!` call JuMP will call the `MOI.empty!` function which first delete the existing SCIPData object, creates a new on, then reinput all the problem in one go. This means that the SCIPData that was created during the `Model(SCIP.Optimizer)` call and the one that is used during the optimization process may differ. 
In the pull request https://github.com/scipopt/SCIP.jl/pull/290, the finalizer was only added to the SCIPData created during the `Model` call. Now the finalizer call is also added to the SCIPData object created during the …
=> Fix Issue With Garbage Collection

src/MOI_wrapper.jl, src/MOI_wrapper/results.jl, test/cutcallback.jl, test/sepa.jl
=> Fix MOI.TerminationStatus

.github/workflows/MINLP.yml, .github/workflows/ci.yml, Project.toml, README.md, deps/build.jl, src/init.jl, test/MINLPTests/Project.toml
=> Enable Windows in CI and remove warnings

src/nonlinear.jl, src/scip_data.jl, src/sepa.jl
I was trying to figure out why https://github.com/scipopt/SCIP.jl/pull/241 was needed. Benchmarking showed some allocations that I didn't expect. Then I found that `unsafe_convert` was typed as `::Any`!
```julia
julia> import SCIP
julia> import MathOptInterface as MOI
julia> model = SCIP.Optimizer();
julia> @time SCIP.SCIPgetSols(model)
0.000005 seconds (2 allocations: 32 bytes)
Ptr{Ptr{Nothing}} @0x0000000000000000
julia> @time SCIP.SCIPgetNSols(model)
0.000007 seconds (1 allocation: 16 bytes)
0
julia> @code_warntype SCIP.SCIPgetNSols(model)
MethodInstance for SCIP.LibSCIP.SCIPgetNSols(::SCIP.Optimizer)
from SCIPgetNSols(scip) @ SCIP.LibSCIP ~/.julia/packages/SCIP/9Wf6c/src/LibSCIP.jl:18286
Arguments
#self#::Core.Const(SCIP.LibSCIP.SCIPgetNSols)
scip::SCIP.Optimizer
Body::Int32
1 ─ %1 = …
```
=> Fix type stability of Base.RefValue fields
