scipopt/SCIP.jl

src/mpb_interface.jl, src/wrapper.jl, test/runtests.jl
=> WIP: implement heur callbacks

src/mpb_interface.jl, src/wrapper.jl, test/runtests.jl
this needs https://github.com/leethargo/CSIP/pull/21
=> enabling qcqpmodel tests doesn't produce errors

src/mpb_interface.jl, src/types.jl, src/wrapper.jl, test/runtests.jl
will work once https://github.com/leethargo/CSIP/pull/22 is accepted
=> support nonlinear models

README.md, deps/build.jl, src/SCIP.jl, src/params.jl, src/wrapper.jl
=> set parameters in a better way

REQUIRE, src/SCIP.jl, src/mpb_interface.jl, src/params.jl, src/types.jl, test/runtests.jl
=> implement solver-independent parameters and fix some compat issues

.travis.yml, REQUIRE, benchmark/sparse_linprog.jl, src/mpb_interface.jl
=> handle sparse rows in `loadproblem!`

src/SCIP.jl, test/REQUIRE, test/mixintprog.jl, test/more_tests.jl, test/runtests.jl
=> Remove FactCheck dependency

src/mpb_interface.jl, src/types.jl, src/wrapper.jl
=> WIP: fix memory leaks

.travis.yml, README.md, deps/build.jl
For #42 
Instead of modifying `Makefile` in `CSIP`, I just added hard coded commands in `build.jl`. I was afraid that direct changes in `CSIP` may affect other linked packages for other languages.
=> build on macOS

deps/csip_version.jl, test/more_tests.jl
=> update CSIP to 0.4.1, add test for #49

README.md
=> add note about OS support

src/MOI_wrapper.jl, src/MOI_wrapper/variable.jl, test/MOI_additional.jl, test/MOI_wrapper.jl
=> Store bounds for binary variables

src/MOI_wrapper.jl, src/MOI_wrapper/linear_constraints.jl, src/MOI_wrapper/objective.jl, src/MOI_wrapper/quadratic_constraints.jl, src/MOI_wrapper/results.jl, src/MOI_wrapper/sos_constraints.jl, src/MOI_wrapper/variable.jl, src/managed_scip.jl, test/MOI_additional.jl, test/managed_scip.jl
=> add unsafe_convert and GC.@preserve for ccalls

src/MOI_wrapper/quadratic_constraints.jl
=> fix scaling of coefficients in quadratic constraints

src/MOI_wrapper/results.jl, test/MOI_additional.jl
=> Check SCIP stage before result queries.

test/MOI_wrapper_direct.jl
=> activate more QCP MOI tests

test/MINLPTests/Project.toml, test/MINLPTests/run_minlptests.jl
Requires new release of MINLPTests with https://github.com/JuliaOpt/MINLPTests.jl/pull/20 merged.
=> simplify usage of MINLPTests (override status codes globally)

gen/Project.toml
I'm not sure CEnum is really needed for the gen part
=> Project.toml for gen folder

src/MOI_wrapper/results.jl, test/MOI_additional.jl
I don't have SCIP installed locally, so didn't test. 
Closes #157
=> Implement MOI.DualStatus

.travis.yml, src/MOI_wrapper/variable.jl
Found this while investigating the SOC business
=> undefined variable

src/MOI_wrapper.jl, src/MOI_wrapper/constraints.jl, src/MOI_wrapper/linear_constraints.jl, src/MOI_wrapper/objective.jl, src/MOI_wrapper/quadratic_constraints.jl, src/MOI_wrapper/variable.jl, src/conshdlr.jl, src/managed_scip.jl, src/nonlinear.jl, src/sepa.jl, src/wrapper.jl, test/conshdlr.jl, test/conshdlr_support.jl, test/cutcallback.jl, test/direct_library_calls.jl, test/managed_scip.jl, test/sepa.jl
Small change to syntax to be more in line with SCIP.
=> SC changed to SCIP_CALL

Project.toml
Freeze version to SCIP 7.0.2 for now because of #196
=> fix jll to 7.0.2

src/MOI_wrapper/constraints.jl, src/MOI_wrapper/linear_constraints.jl, src/MOI_wrapper/quadratic_constraints.jl, src/MOI_wrapper/variable.jl, test/MOI_wrapper_bridged.jl, test/MOI_wrapper_cached.jl, test/MOI_wrapper_direct.jl, test/runtests.jl
Finding a variable from a name string was necessary for many tests, I also checked carefully which tests could pass on the cached model vs bridged vs direct
=> Find var name, additional tests

.github/workflows/ci.yml, Project.toml, src/MOI_wrapper.jl, src/MOI_wrapper/abspower_constraints.jl, src/MOI_wrapper/indicator_constraints.jl, src/MOI_wrapper/linear_constraints.jl, src/MOI_wrapper/quadratic_constraints.jl, src/MOI_wrapper/soc_constraints.jl, src/MOI_wrapper/sos_constraints.jl, src/MOI_wrapper/variable.jl, src/init.jl
factorize the MOI.delete function for general function and set
=> common delete

test/runtests.jl
=> remove SOC test

src/nonlinear.jl, test/MOI_nonlinear_exprs.jl, test/runtests.jl
Attempt at https://github.com/scipopt/SCIP.jl/issues/166
ping @remi-garcia we can finally have almost arbitrary expressions
=> Eval values

src/MOI_wrapper/variable.jl
For GreaterThan constraints, only the lower bound of the variable should be changed, similarly for LessThan constraints.
=> MOI.set fixed

README.md
x-ref: https://github.com/JuliaPackaging/Yggdrasil/issues/5651
=> Tell users to read license restrictions in README

test/MOI_additional.jl
a test assumes the partial solution will necessarily be the one kept by the solver
=> relax test assumption on repaired solution

src/MOI_wrapper/variable.jl
binary bounds were not tracked properly when modifying a ConstraintSet, so fixing binaries
=> binbounds fixed

README.md
=> change readme for jump

.codecov.yml, src/MOI_wrapper.jl, src/MOI_wrapper/heuristic.jl, src/SCIP.jl, src/heuristic.jl, src/scip_data.jl, test/cutcallback.jl, test/heuristic.jl, test/runtests.jl
This introduces the heuristic plugin in the wrapper.
The MOI wrapper level will come in another one
=> Heuristic plugin

src/MOI_wrapper.jl, src/MOI_wrapper/heuristic.jl, src/heuristic.jl, test/cutcallback.jl, test/heuristic.jl
Following #269, adds heuristic at the MOI level, allowing a simpler interface than the SCIP one
ping @mrmoustachie, @mmghannam  following Friday's sprint
=> heuristic callback in MOI

src/MOI_wrapper.jl
Closes https://github.com/scipopt/SCIP.jl/issues/304
=> Fix modification when stage is left in SCIP_STAGE_SOLVING

src/MOI_wrapper.jl, src/MOI_wrapper/constraints.jl, test/MOI_tests.jl
=> Fix MOI.ConstraintName

src/MOI_wrapper.jl, src/MOI_wrapper/UserCutCallback.jl, src/MOI_wrapper/linear_constraints.jl, src/MOI_wrapper/quadratic_constraints.jl, src/MOI_wrapper/variable.jl, test/MOI_tests.jl
=> Fix LowerBoundAlreadySet and UpperBoundAlreadySet

src/MOI_wrapper/variable.jl, test/MOI_tests.jl
=> Fix deleting from .constypes when deleting MOI.VariableIndex

Project.toml, src/init.jl
Probably needs https://github.com/JuliaPackaging/Yggdrasil/pull/11175
=> Revert to using SCIP_PaPILO on Windows

Project.toml, README.md
=> Prep for v0.12.5
